# Generated by Django 4.0 on 2021-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeLocation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('harvestTime', models.DateTimeField(null=True)),
                ('stationID', models.IntegerField(null=True)),
                ('availableBikeStands', models.IntegerField(null=True)),
                ('bikeStands', models.IntegerField(null=True)),
                ('availableBikes', models.IntegerField(null=True)),
                ('banking', models.BooleanField(null=True)),
                ('bonus', models.BooleanField(null=True)),
                ('lastUpdate', models.DateTimeField(null=True)),
                ('status', models.TextField(max_length=10, null=True)),
                ('address', models.TextField(max_length=50, null=True)),
                ('name', models.TextField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
